export const pasosDeBaile = [
        {
        nombre: "Swing Out",
        duracion: 8,
        inicio: ["cerrada", "abierta"],
        fin: "abierta",
        categoria: "Pasos Básicos",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: false,
        },
        {
        nombre: "Circulo",
        duracion: 8,
        inicio: ["abierta", "cerrada"],
        fin: "cerrada",
        categoria: "Pasos Básicos",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        mismoFrente: true,
        rotacionInicio: false,
        },
        {
        nombre: "Pass By",
        duracion: 6,
        inicio: "abierta",
        fin: "abierta",
        categoria: "Pasos Básicos",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        mismoFrente: false,
        rotacionInicio: false,
        },
        {
        nombre: "Tuck Turn",
        duracion: 6,
        inicio: "cerrada",
        fin: "abierta",
        categoria: "Pasos Básicos",
        frente: "izquierda-derecha",
        mismoFrente: true,
        rotacionInicio: true,
        rotacionFin: true
        },
        {
        nombre: "Sugar Push",
        duracion: 6,
        inicio: "abierta",
        fin: "abierta",
        categoria: "Pasos Clásicos",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        mismoFrente: true,
        rotacionInicio: false,
        },
        {
        nombre: "Tuck Turn 4",
        duracion: 4,
        inicio: "abierta",
        fin: "abierta",
        categoria: "Pasos Intermedios",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        mismoFrente: true,
        rotacionInicio: true,
        rotacionFin: true
        },
        {
        nombre: "Bring In 4",
        duracion: 4,
        inicio: "abierta",
        fin: "cerrada",
        categoria: "Pasos Intermedios",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: false,
        rotacionFin: false
        },
        {
        nombre: "Send Out",
        duracion: 6,
        inicio: "cerrada",
        fin: "abierta",
        categoria: "Pasos Básicos",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: false,
        },
        {
        nombre: "Gig Walk",
        duracion: 6,
        inicio: "cerrada",
        fin: "cerrada",
        categoria: "Pasos Clásicos",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        mismoFrente: true
        },
        {
        nombre: "Semi Circle",
        duracion: 6,
        inicio: ["cerrada", "abierta"],
        fin: "cerrada",
        categoria: "Pasos Básicos",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        mismoFrente: false,
        rotacionInicio: false,
        },
        {
        nombre: "Contra Giro",
        duracion: 6,
        inicio: "abierta",
        fin: ["abierta", "cerrada"],
        categoria: "Pasos Básicos",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        mismoFrente: true,
        rotacionInicio: true,
        rotacionFin: true
        },
        {
        nombre: "Tuck Turn Doble",
        duracion: 8,
        inicio: "cerrada",
        fin: ["abierta", "cerrada"],
        categoria: "Pasos Intermedios",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        rotacionInicio: true,
        rotacionFin: true
        },
        {
        nombre: "Texas Tommy",
        duracion: 8,
        inicio: ["cerrada", "abierta"],
        fin: "abierta",
        categoria: "Pasos Clásicos",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: false,
        },
        {
        nombre: "Quickstop",
        duracion: 8,
        inicio: "abierta",
        fin: "abierta",
        categoria: "Pasos Clásicos",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: false,
        },
        {
        nombre: "Pecking",
        duracion: 8,
        inicio: ["abierta", "cerrada"],
        fin: ["abierta", "cerrada"],
        categoria: "Pasos Clásicos",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        rotacionInicio: false,
        },
        {
        nombre: "Arm Roll",
        duracion: 8,
        inicio: "abierta",
        fin: "abierta",
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: true,
        rotacionFin: true
        },
        {  
        nombre: "Click Click",
        duracion: 8,    
        inicio: "abierta",    
        fin: ["abierta", "cerrada"],
        categoria: "Pasos Intermedios",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        rotacionInicio: false,
        rotacionFin: true
      },
      {
        nombre: "Carpita Skye",
        duracion: 8,
        inicio: "abierta",
        fin: "abierta",
        categoria: "Pasos Básicos",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: false,
        rotacionFin: false
      },
      {
        nombre: "Skye Send Out KBC",
        duracion: 8,
        inicio: "cerrada",
        fin: ["abierta", "cerrada"],
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha"],
        rotacionInicio: true,
        rotacionFin: true
      },
      {
        nombre: "Slingshot",
        duracion: 8,
        inicio: ["abierta", "cerrada"],
        fin: "cerrada",
        categoria: "Pasos Intermedios",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionFin: true
      },
      {
        nombre: "Fake Hide",
        duracion: 8,
        inicio: "abierta",
        fin: "abierta",
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: false,
      },
      {
        nombre: "Mini Dip",
        duracion: 8,
        inicio: "abierta",
        fin: ["abierta", "cerrada"],
        categoria: "Pasos Clásicos",
        frente: ["izquierda-derecha"],
      },
      {
        nombre: "Tuck Turn KBC",
        duracion: 8,
        inicio: "cerrada",
        fin: "abierta",
        categoria: "Pasos Intermedios",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: true,
        rotacionFin: true
      },
      {
        nombre: "Rocks Break 7",
        duracion: 8,
        inicio: "cerrada",
        fin: "cerrada",
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        mismoFrente: true,
      },
      {
        nombre: "Flying Bird",
        duracion: 10,
        inicio: "cerrada",
        fin: "cerrada",
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha"],
        mismoFrente: true
      },
      {
        nombre: "Carroussell Juani",
        duracion: 10,
        inicio: "abierta",
        fin: ["abierta", "cerrada"],
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha"],
        rotacionInicio: true,
      },
      {
        nombre: "Sugar Push al reves",
        duracion: 14,
        inicio: "cerrada",
        fin: ["abierta", "cerrada"],
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        mismoFrente: true,
        rotacionInicio: false,
      },
      {
        nombre: "Peter & Max",
        duracion: 10,
        inicio: "abierta",
        fin: "cerrada",
        categoria: "Pasos Flasheros",
        frente: ["derecha-izquierda"],
        mismoFrente: false
      },
      {
        nombre: "Mini Dip KBC",
        duracion: 10,
        inicio: "abierta",
        fin: "abierta",
        categoria: "Pasos Clásicos",
        frente: ["izquierda-derecha"],
        mismoFrente: true
      },
      {
        nombre: "Break Stomps",
        duracion: 10,
        inicio: "cerrada",
        fin: "cerrada",
        categoria: "Pasos Clásicos",
        frente: ["izquierda-derecha"],
        mismoFrente: true
      },
      {
        nombre: "Swing Out Slingshot",
        duracion: 10,
        inicio: ["abierta", "cerrada"],
        fin: ["abierta", "cerrada"],
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionFin: true
      },
      {
        nombre: "Swing Out In & Out",
        duracion: 10,
        inicio: "cerrada",
        fin: "abierta",
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: false,
      },
      {
        nombre: "Back carleston Into Rocks",
        duracion: 18,
        inicio: "cerrada",
        fin: "cerrada",
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: true,
      },
      {
        nombre: "Sugar Push 3Step",
        duracion: 12,
        inicio: ["abierta", "cerrada"],
        fin: "abierta",
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: false,
      },
      {
        nombre: "Swing Out R&G",
        duracion: 12,
        inicio: ["abierta", "cerrada"],
        fin: "abierta",
        categoria: "Pasos Intermedios",
        frente: ["izquierda-derecha"],
        mismoFrente: true
      },
      {
        nombre: "Círculo R&G",
        duracion: 12,
        inicio: ["abierta", "cerrada"],
        fin: "cerrada",
        categoria: "Pasos Básicos",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        mismoFrente: true
      },
      {
        nombre: "Swing Out Break 6",
        duracion: 12,
        inicio: "cerrada",
        fin: "abierta",
        categoria: "Pasos Intermedios",
        frente: ["izquierda-derecha", "derecha-izquierda"],
        mismoFrente: true
      },
      {
        nombre: "Swing Out Chest Turn",
        duracion: 12,
        inicio: "cerrada",
        fin: "abierta",
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: false,
        rotacionFin: false
      },
      {
        nombre: "Contragiro Armwork Together",
        duracion: 22,
        inicio: "abierta",
        fin: ["abierta", "cerrada"],
        categoria: "Pasos Flasheros",
        frente: ["derecha-izquierda"],
        mismoFrente: true,
        rotacionInicio: true,
      },
      {
        nombre: "Texas tomy Around",
        duracion: 16,
        inicio: "abierta",
        fin: "abierta",
        categoria: "Pasos Intermedios",
        frente: ["derecha-izquierda"],
        mismoFrente: false
      },
      {
        nombre: "Sugar Push GW barrell",
        duracion: 16,
        inicio: ["abierta", "cerrada"],
        fin: "abierta",
        categoria: "Pasos Flasheros",
        frente: ["derecha-izquierda"],
        mismoFrente: false,
        rotacionInicio: false,
      },
      {
        nombre: "Stomps Side by Side",
        duracion: 10,
        inicio: "abierta",
        fin: "abierta",
        categoria: "Pasos Flasheros",
        frente: ["izquierda-derecha"],
        mismoFrente: true
      },
      {
        nombre: "Frankie Around",
        duracion: 12,
        inicio: "abierta",
        fin: "cerrada",
        categoria: "Pasos Clásicos",
        frente: ["izquierda-derecha"],
        mismoFrente: false,
        rotacionInicio: true,
        rotacionFin: true
      },
      {
        nombre: "Sendout Tackie Annie",
        duracion: 12,
        inicio: "cerrada",
        fin: "abierta",
        categoria: "Pasos Intermedios",
        frente: ["izquierda-derecha"],
        mismoFrente: true,
        rotacionInicio: false,
      },
  ];

 